[package]
name = "lorry-template"
version = "0.1.0"
authors = ["Jakob Neufeld <jakob.n.neufeld@gamil.com>"]
edition = "2018"
build = "spec.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[build-dependencies]
lorry = "0.1.5"

[dependencies]
